FROM node:20-alpine AS base

FROM base AS builder
RUN apk update
RUN apk add --no-cache libc6-compat
RUN npm install -g pnpm
RUN npm install -g turbo@2.2.3

WORKDIR /app
COPY . .
RUN turbo prune web --docker


FROM base AS installer
RUN npm install -g pnpm
RUN npm install -g turbo@2.2.3
RUN apk add --no-cache nginx


WORKDIR /app
COPY --from=builder /app/out/json/ .
RUN pnpm install
COPY --from=builder /app/out/full/ .
RUN turbo build


FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_PUBLIC_API_DOMAIN=http://spec-stroy-resource-api:3001


WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public

COPY /apps/web/nginx.conf /etc/nginx/nginx.conf


CMD ["sh", "-c", "nginx -g 'daemon off;' & node apps/web/server.js"]