import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google"
import "@/globals.css";
import styles from "./layout.module.css"
import Footer from "./components/Footer/Footer";
import Call from "./components/Call/Call";

const roboto = Roboto_Flex({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" >
      <body className={ roboto.className }>
        <div className={ styles.wrapper }>
          <div className={ styles.body }>
            { children }
          </div>
          <Call className={ styles.call } />
          <Footer className={ styles.footer } />
        </div>
      </body>

    </html >
  );
}
