FROM ubuntu:22.04

# Читаем переменные среды
ARG DOMAIN_EMAIL
ARG DOMAIN_URL

# Устанавливаем переменные среды
ENV DOMAIN_EMAIL=$DOMAIN_EMAIL
ENV DOMAIN_URL=$DOMAIN_URL

WORKDIR /certbot

# Копируем все файлы из текущей директории в рабочую директорию контейнера
COPY . .

# Обновляем пакеты и устанавливаем certbot
RUN apt-get update && apt-get -y install certbot



# Запускаем скрипт генерации сертификатов
CMD ["sh", "./generate-certificate.sh"]
