import styles from "./layout.module.css";

export const metadata = {
  title: "login",
  description: "Generated by Next.js",
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={styles.wrapper}>
      <div className={styles.body}>{children}</div>
    </div>
  );
}
