FROM node:20-alpine AS builder

WORKDIR /app
COPY /apps/web/package.json /app/apps/web/package.json
COPY tsconfig.json .
WORKDIR /app/apps/web
RUN npm install

COPY  /apps/web/ .
RUN npm run build

FROM node:20-alpine AS production

RUN apk add --no-cache nginx

WORKDIR /app
ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/apps/web/public .
RUN mkdir .next
RUN chown nextjs:nodejs .next
COPY --from=builder /app/apps/web/.next/standalone ./
COPY --from=builder /app/apps/web/.next/static ./.next/static

COPY /apps/web/nginx.conf /etc/nginx/nginx.conf


CMD ["sh", "-c", "nginx -g 'daemon off;' & node server.js"]