import { Inter } from "next/font/google";
import "@/globals.css";

const DMSans = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "admin",
  description: "Generated by Next.js",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={DMSans.className}>{children}</body>
    </html>
  );
}
