import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Проекты",
  description: "Generated by create next app",
};
export default function ProjectLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div>{children}</div>;
}
