import { Metadata } from "next";
import SubHeader from "./components/SubHeader/SubHeader";
import styles from "./layout.module.css";

export const metadata: Metadata = {
  title: "Проекты",
  description: "Generated by create next app",
};

export default function ProjectLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={styles.wrapper}>
      <SubHeader className={styles.header} />
      <div className={styles.body}>{children}</div>
    </div>
  );
}
