import { Metadata } from "next";
import SubHeader from "./components/SubHeader/SubHeader";
import styles from "./layout.module.css";
import CallForm from "@/components/CallForm/CallForm";

export const metadata: Metadata = {
  title: "Проекты",
  description: "Generated by create next app",
};

export default function ProjectLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={styles.wrapper}>
      <div className={styles.header}>
        <SubHeader />
      </div>
      <div className={styles.body}>{children}</div>
      <div className={styles.call}>
        <CallForm />
      </div>
    </div>
  );
}
