name: Create and publish a Docker image

on: [workflow_dispatch]

env:
    REGISTRY: ghcr.io
    API_IMAGE_NAME: ${{ github.repository }}-api
    WEB_IMAGE_NAME: ${{ github.repository }}-web
    BACKUP_IMAGE_NAME: ${{ github.repository }}-db-backup
    CERTBOT_IMAGE_NAME: ${{ github.repository }}-certbot

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GH_PAT }}

            # Build and push API image
            - name: Extract metadata (tags, labels) for Docker
              id: meta-api
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch
                      type=sha
                      latest

            - name: Build and push Docker image (API)
              uses: docker/build-push-action@v6
              with:
                  context: ./
                  file: ./Dockerfile.api
                  push: true
                  tags: |
                      ${{ steps.meta-api.outputs.tags }}
                      ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:latest
                  labels: ${{ steps.meta-api.outputs.labels }}

            # Build and push Web image
            - name: Extract metadata for Web
              id: meta-web
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.WEB_IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch
                      type=sha
                      latest

            - name: Build and push Docker image (Web)
              uses: docker/build-push-action@v6
              with:
                  context: ./
                  file: ./Dockerfile.web
                  push: true
                  tags: |
                      ${{ steps.meta-web.outputs.tags }}
                      ${{ env.REGISTRY }}/${{ env.WEB_IMAGE_NAME }}:latest
                  labels: ${{ steps.meta-web.outputs.labels }}

            # Build and push db-backup image
            - name: Extract metadata for db-backup
              id: meta-db-backup
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.BACKUP_IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch
                      type=sha
                      latest

            - name: Build and push Docker image (db-backup)
              uses: docker/build-push-action@v6
              with:
                  context: ./
                  file: ./Dockerfile.backup
                  push: true
                  tags: |
                      ${{ steps.meta-db-backup.outputs.tags }}
                      ${{ env.REGISTRY }}/${{ env.BACKUP_IMAGE_NAME }}:latest
                  labels: ${{ steps.meta-db-backup.outputs.labels }}

            # Build and push certbot image
            - name: Extract metadata for certbot
              id: meta-certbot
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.CERTBOT_IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch
                      type=sha
                      latest

            - name: Build and push Docker image (certbot)
              uses: docker/build-push-action@v6
              with:
                  context: ./
                  file: ./Dockerfile.certbot
                  push: true
                  tags: |
                      ${{ steps.meta-certbot.outputs.tags }}
                      ${{ env.REGISTRY }}/${{ env.CERTBOT_IMAGE_NAME }}:latest
                  labels: ${{ steps.meta-certbot.outputs.labels }}
